LOAD DATA LOCAL INFILE 'user.txt' INTO TABLE User
FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'item.txt' INTO TABLE Item
FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'category.txt' INTO TABLE Category
FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'belong.txt' INTO TABLE Belong
FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'bid.txt' INTO TABLE Bid
FIELDS TERMINATED BY '|*|';